### ISSUE TITLE
no active device found

### ISSUE THREAD

**Issue by Whovian76** [TimeToogo/spotify-hr#13]
I have trouble shot this over and over. No active device found open in the app. I have opened spotify and fitbit. I have even force stopped fitbit and reloaded still the same error message! Why have an app if its not going to work?!?@

**Comment by melloandrea** [comment]
The same to me. Did you solve it?

**Comment by EmmaGX** [comment]
No. I'm very disappointed

**Comment by TimeToogo** [comment]
Hi,

Please ensure that:
1. Your FitBit device is connected to your phone via Bluetooth and FitBit app is running in the background. 
2. That Spotify is running and open on your device. 
3. That you’ve logged into the same Spotify account on FitBit and on the Spotify app. 
4. That you have a premium Spotify account. 

Please let me know what devices & models you are using if the problem persists. 
Thanks

**Comment by bking30** [comment]
I have the Fitbit ionic, iPhone 7s. I have tried all the troubleshooting you have described above and still I am sitting at the screen that says no active device. 
Although I will say when I initially set up my device it logged in and asks to log into my Spotify account and when I look at the account on the Fitbit app on my phone it says the account name is null

**Comment by tv1992** [comment]
@timetogoo I have the same problem but maybe I logged in on a different spotify account. But how can I undo this? Because when I log out I can’t select an other account.
