### ISSUE TITLE
Connecting error

### ISSUE THREAD

**Issue by apetri89** [TimeToogo/spotify-hr#14]
I've logged on spotify via phone and Fitbit app settings but when I go to open up the hr app on my versa it keeps saying Connecting. Lost connection to the FitBit app

**Comment by TimeToogo** [comment]
That means your FitBit is not able to connect to your phone via Bluetooth. Please ensure that:

1. You are close to your phone. 
2. Your phone has Bluetooth enabled. 
3. The FitBit app is running the background on your phone.
