### ISSUE TITLE
Not responding to touch

### ISSUE THREAD

**Issue by jbusam0001** [TimeToogo/spotify-hr#21]
App will not allow me to change song on fitbit versa

**Comment by skinni44** [comment]
I need this sorting aswell, won’t work atall for me. Will show song but won’t control Spotify. Can we get this sorted please. Cheers

**Comment by jbusam0001** [comment]
Yeah i see song and all playlist but can not use the controls

**Comment by TimeToogo** [comment]
Unfortunately controlling playback requires a Premium Spotify account. This is restriction imposed by the Spotify Web API and is out of my control. Apologies for the inconvenience.

Source: https://github.com/spotify/web-api/issues/1089
