### ISSUE TITLE
Same as others, doesn’t control anything

### ISSUE THREAD

**Issue by skinni44** [TimeToogo/spotify-hr#22]
My versa connects to my phone and account as the song shows up on the watch but it won’t control playlist. Can we get this sorted please if it’s something I’m doing wrong I’d like to know pretty quick. Thanks

**Comment by skinni44** [comment]
No I don’t. Surely I shouldn’t have to? It shows my playlists but when I select one it says I have inactive device please open etc which it is already then won’t actually play the selected playlist.

So all the information is being shown but nothing is communicating. The sound is getting interrupted in my Bluetooth headphones when the watch can’t see them so that’s ok but it’s not working as a remote.

**Comment by TimeToogo** [comment]
Unfortunately controlling playback requires a Premium Spotify account. This is restriction imposed by the Spotify Web API and is out of my control. Apologies for the inconvenience.

Source: https://github.com/spotify/web-api/issues/1089
