### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by ithernet** [TimeToogo/spotify-hr#29]
Trying to log out  from Spotify and login with another account. However when I log out and click login, it automatically logs me in with my old accout that i logged out from.

**Comment by annJohann** [comment]
I have the same problem. Did you find the answer yet?

**Comment by TimeToogo** [comment]
See https://github.com/TimeToogo/spotify-hr/issues/7#issuecomment-435029575

**Comment by annJohann** [comment]
Thanks. This works. 👍
