### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by ranajodavid** [TimeToogo/spotify-hr#33]
Can’t get app to log in to Spotify. Have tried uninstalling and reinstalling app, restarting Fitbit versa, logging out of Spotify website and iPhone app before signing in via this app. I’ve also tried changing my Spotify password and verifying that it worked through website and iPhone app.  I’m out of ideas.

**Comment by xeryus-velasco** [comment]
Same; Everytime I press the login button, it opens a browser but jumps out of it almost immediately and back to the apps settings page. I've tried to clock the three dots in the upper right corner when the in app web browser pops up so I can open it in Firefox. But once I open the new tab in Firefox, it closes the tab and jumps back to the apps settings page with the login button still saying 'Login'.

**Comment by xeryus-velasco** [comment]
@xeryus-velasco issue seems to be resolved now; atleast for me.

**Comment by ranajodavid** [comment]
Copied and pasted the login page url from safari into chrome and it worked.
