### ISSUE TITLE
No option to sign in under different Spotify accoubt

### ISSUE THREAD

**Issue by ShanD-Oops** [TimeToogo/spotify-hr#34]
I signed in through the Fitbit app to Spotify and accidentally used my husband’s account instead of mine. Stupid, I know. Now I cannot reset it at all. I’ve logged out, removed the app, removed the FitBit, reset everything. Every time I retry it the app automatically defaults to my husband’s Spotify account. This sucks.

**Comment by Arkanah57** [comment]
I also have this issue. Have tried uninstalling and reinstalling but it didnt help

**Comment by lisawagner2003** [comment]
I have the same problem as well.

**Comment by TimeToogo** [comment]
See #7
