### ISSUE TITLE
Spotify hr isn’t working on my Fitbit 

### ISSUE THREAD

**Issue by Lanal22** [TimeToogo/spotify-hr#36]
The Spotify hr remote controller for my Spotify app isn’t controlling it

**Comment by titerousse** [comment]
Same here :-/ the app shows the song playing but can't control it

**Comment by Lanal22** [comment]
Yeah ikr

**Comment by tracyt0828** [comment]
Spotify HR not working at all on Fitbit-won’t let me login to Spotify from Fitbit app

**Comment by TimeToogo** [comment]
Unfortunately controlling playback requires a Premium Spotify account. This is restriction imposed by the Spotify Web API.

**Comment by tracyt0828** [comment]
I do have a Premium account-have had it for years. Your app does not work.

**Comment by TimeToogo** [comment]
@tracyt0828 Can you please describe your issue and the steps to reproduce it?
Please include the model of your FitBit and phone.

**Comment by tracyt0828** [comment]
When I am in the Fitbit app and try to login to Spotify it just goes back to the login screen and doesn’t let me login to my account. I have Fitbit Versa, and iPhone 8+.

**Comment by TimeToogo** [comment]
@tracyt0828 try these instructions: https://github.com/TimeToogo/spotify-hr/issues/7#issuecomment-435029575

**Comment by tracyt0828** [comment]
I followed the instructions; I get to the login and then when I press “open” it just goes back to the Spotify HR login in the settings
