### ISSUE TITLE
Can't change login account 

### ISSUE THREAD

**Issue by Laura7979** [TimeToogo/spotify-hr#43]
When I first installed the app, I accidentally signed in with an old Spotify account that wasn't working on my Versa Lite. I wanted to change it to my current Spotify account and I tried uninstalling the app, cleaning my cache partition on my phone and even cleaning my fifbit cache, but when I click on the app to login, it still shows the original address I signed into with. Is there a way I can fix this so I can change my login for this app?

**Comment by ZimbiX** [comment]
See https://github.com/TimeToogo/spotify-hr/issues/7#issuecomment-435029575
