### ISSUE TITLE
Can't use controls

### ISSUE THREAD

**Issue by RobyMango** [TimeToogo/spotify-hr#6]
Hi,
I downloaded Spotify HR but can't use it..
I tried to login from the smartphone but it didn't ask for login details, it logged me in as "null".
I then opened the app from the Versa, while playing Spotify on the smartphone, and it only displays "No active device found. Please open Spotify on your device."
If I navigate to "Choose Playlist", I see the main one as "Unknown" but the top and bottom ones are actually my playstists. As soon as I touch the screen again, it goes back to "No active device found. etc..".
Could you please help with this issue?
I am currently using:
Honor 8 FRD-L09 with Android 8.0
Spotify v.8.4.70.666
Fitbit Versa
Spotify HR v.0.2.3
Thank you,
Roberto

EDIT: After restarting the Versa, it connected and does show the currently playing song, but still none of the controls work. I tried pausing, skipping tracks and changing playlists but nothing worked.

**Comment by TimeToogo** [comment]
A premium Spotify account is required to use this app. This app uses the web API which is only fully enabled on premium accounts.
