### ISSUE TITLE
Can't use the controls 

### ISSUE THREAD

**Issue by Oktoroc** [TimeToogo/spotify-hr#9]
Heyo, I'm using Spotify HR and none of the controls will work. I can't edit volume, switch playlists, use the player, and the heart rate shuffle won't work, either. I am properly logged in to Spotify, by the way, and it reads my music, but other than that, nothing works.

**Comment by eXodusK3** [comment]
I am having the same issue.  

Logged in correctly.  Shows correct song playing and my playlists but none of the buttons (play/pause, next etc) does not work when I push them.

**Comment by TimeToogo** [comment]
A premium Spotify account is required to use this app. This app uses the web API which is only fully enabled on premium accounts.
